### ISSUE TITLE
exit status 1 expected unqualified-id before 'bool'

### ISSUE THREAD

**Issue by he77PC011** [cyberangel22k/FUGU-ARDUINO-MPPT-FIRMWARE#4]
^~~~~~~~~~~~~
                                 currentSensV
F:\mppt-wifi\ARDUINO_MPPT_FIRMWARE_V1.1\8_LCD_Menu.ino: In function 'void displayConfig3()':
8_LCD_Menu:63:6: error: 'Wh' was not declared in this scope
   if(Wh<10){lcd.print(Wh,2);lcd.print("Wh ");}                 //9.99Wh_
      ^~
8_LCD_Menu:66:31: error: 'kWh' was not declared in this scope
   else if(Wh<10000){lcd.print(kWh,1);lcd.print("kWh ");}       //9.9kWh_
                               ^~~
8_LCD_Menu:67:32: error: 'kWh' was not declared in this scope
   else if(Wh<100000){lcd.print(kWh,0);lcd.print("kWh  ");}     //99kWh__
                                ^~~
8_LCD_Menu:68:33: error: 'kWh' was not declared in this scope
   else if(Wh<1000000){lcd.print(kWh,0);lcd.print("kWh ");}     //999kWh_
                                 ^~~
8_LCD_Menu:69:34: error: 'MWh' was not declared in this scope
   else if(Wh<10000000){lcd.print(MWh,1);lcd.print("MWh ");}    //9.9MWh_
                                  ^~~
8_LCD_Menu:70:35: error: 'MWh' was not declared in this scope
   else if(Wh<100000000){lcd.print(MWh,0);lcd.print("MWh  ");}  //99MWh__
                                   ^~~
8_LCD_Menu:71:36: error: 'MWh' was not declared in this scope
   else if(Wh<1000000000){lcd.print(MWh,0);lcd.print("MWh ");}  //999Mwh_
                                    ^~~
F:\mppt-wifi\ARDUINO_MPPT_FIRMWARE_V1.1\8_LCD_Menu.ino: In function 'void LCD_Menu()':
8_LCD_Menu:142:10: error: 'MPPT_Mode' was not declared in this scope
       if(MPPT_Mode==1){lcd.print("MPPT + CC-CV  ");}
          ^~~~~~~~~
8_LCD_Menu:146:37: error: 'MPPT_Mode' was not declared in this scope
       if(setMenuPage==0){boolTemp = MPPT_Mode;}
                                     ^~~~~~~~~
8_LCD_Menu:150:14: error: 'MPPT_Mode' was not declared in this scope
           if(MPPT_Mode==1){MPPT_Mode=0;}else{MPPT_Mode=1;}
              ^~~~~~~~~
8_LCD_Menu:152:75: error: 'MPPT_Mode' was not declared in this scope
         if(digitalRead(buttonBack)==1){while(digitalRead(buttonBack)==1){}MPPT_Mode = boolTemp;cancelledMessageLCD();setMenuPage=0;}
                                                                           ^~~~~~~~~
8_LCD_Menu:162:10: error: 'output_Mode' was not declared in this scope
       if(output_Mode==1){lcd.print("CHARGER MODE  ");}
          ^~~~~~~~~~~
8_LCD_Menu:166:37: error: 'output_Mode' was not declared in this scope
       if(setMenuPage==0){boolTemp = output_Mode;}
                                     ^~~~~~~~~~~
8_LCD_Menu:170:14: error: 'output_Mode' was not declared in this scope
           if(output_Mode==1){output_Mode=0;}else{output_Mode=1;}
              ^~~~~~~~~~~
8_LCD_Menu:172:75: error: 'output_Mode' was not declared in this scope
         if(digitalRead(buttonBack)==1){while(digitalRead(buttonBack)==1){}output_Mode = boolTemp;cancelledMessageLCD();setMenuPage=0;}
                                                                           ^~~~~~~~~~~
8_LCD_Menu:187:26: error: 'floatTemp' was not declared in this scope
       if(setMenuPage==0){floatTemp = voltageBatteryMax;}
                          ^~~~~~~~~
F:\mppt-wifi\ARDUINO_MPPT_FIRMWARE_V1.1\8_LCD_Menu.ino:187:26: note: suggested alternative: 'intTemp'
       if(setMenuPage==0){floatTemp = voltageBatteryMax;}
                          ^~~~~~~~~
                          intTemp
8_LCD_Menu:189:95: error: 'floatTemp' was not declared in this scope
         if(digitalRead(buttonBack)==1){while(digitalRead(buttonBack)==1){}voltageBatteryMax = floatTemp;cancelledMessageLCD();setMenuPage=0;}
                                                                                               ^~~~~~~~~
F:\mppt-wifi\ARDUINO_MPPT_FIRMWARE_V1.1\8_LCD_Menu.ino:189:95: note: suggested alternative: 'intTemp'
         if(digitalRead(buttonBack)==1){while(digitalRead(buttonBack)==1){}voltageBatteryMax = floatTemp;cancelledMessageLCD();setMenuPage=0;}
                                                                                               ^~~~~~~~~
                                                                                               intTemp
8_LCD_Menu:191:9: error: 'currentMenuSetMillis' was not declared in this scope
         currentMenuSetMillis = millis();
         ^~~~~~~~~~~~~~~~~~~~
F:\mppt-wifi\ARDUINO_MPPT_FIRMWARE_V1.1\8_LCD_Menu.ino:191:9: note: suggested alternative: 'currentSens'
         currentMenuSetMillis = millis();
         ^~~~~~~~~~~~~~~~~~~~
         currentSens
8_LCD_Menu:233:26: error: 'floatTemp' was not declared in this scope
       if(setMenuPage==0){floatTemp = voltageBatteryMin;}
                          ^~~~~~~~~
F:\mppt-wifi\ARDUINO_MPPT_FIRMWARE_V1.1\8_LCD_Menu.ino:233:26: note: suggested alternative: 'intTemp'
       if(setMenuPage==0){floatTemp = voltageBatteryMin;}
                          ^~~~~~~~~
                          intTemp
8_LCD_Menu:235:95: error: 'floatTemp' was not declared in this scope
         if(digitalRead(buttonBack)==1){while(digitalRead(buttonBack)==1){}voltageBatteryMin = floatTemp;cancelledMessageLCD();setMenuPage=0;}
                                                                                               ^~~~~~~~~
F:\mppt-wifi\ARDUINO_MPPT_FIRMWARE_V1.1\8_LCD_Menu.ino:235:95: note: suggested alternative: 'intTemp'
         if(digitalRead(buttonBack)==1){while(digitalRead(buttonBack)==1){}voltageBatteryMin = floatTemp;cancelledMessageLCD();setMenuPage=0;}
                                                                                               ^~~~~~~~~
                                                                                               intTemp
8_LCD_Menu:237:9: error: 'currentMenuSetMillis' was not declared in this scope
         currentMenuSetMillis = millis();
         ^~~~~~~~~~~~~~~~~~~~
F:\mppt-wifi\ARDUINO_MPPT_FIRMWARE_V1.1\8_LCD_Menu.ino:237:9: note: suggested alternative: 'currentSens'
         currentMenuSetMillis = millis();
         ^~~~~~~~~~~~~~~~~~~~
         currentSens
8_LCD_Menu:279:26: error: 'floatTemp' was not declared in this scope
       if(setMenuPage==0){floatTemp = currentCharging;}
                          ^~~~~~~~~
F:\mppt-wifi\ARDUINO_MPPT_FIRMWARE_V1.1\8_LCD_Menu.ino:279:26: note: suggested alternative: 'intTemp'
       if(setMenuPage==0){floatTemp = currentCharging;}
                          ^~~~~~~~~
                          intTemp
8_LCD_Menu:281:93: error: 'floatTemp' was not declared in this scope
         if(digitalRead(buttonBack)==1){while(digitalRead(buttonBack)==1){}currentCharging = floatTemp;cancelledMessageLCD();setMenuPage=0;}
                                                                                             ^~~~~~~~~
F:\mppt-wifi\ARDUINO_MPPT_FIRMWARE_V1.1\8_LCD_Menu.ino:281:93: note: suggested alternative: 'intTemp'
         if(digitalRead(buttonBack)==1){while(digitalRead(buttonBack)==1){}currentCharging = floatTemp;cancelledMessageLCD();setMenuPage=0;}
                                                                                             ^~~~~~~~~
                                                                                             intTemp
8_LCD_Menu:283:9: error: 'currentMenuSetMillis' was not declared in this scope
         currentMenuSetMillis = millis();
         ^~~~~~~~~~~~~~~~~~~~
F:\mppt-wifi\ARDUINO_MPPT_FIRMWARE_V1.1\8_LCD_Menu.ino:283:9: note: suggested alternative: 'currentSens'
         currentMenuSetMillis = millis();
         ^~~~~~~~~~~~~~~~~~~~
         currentSens
8_LCD_Menu:321:10: error: 'enableFan' was not declared in this scope
       if(enableFan==1){lcd.print("ENABLED       ");}
          ^~~~~~~~~
8_LCD_Menu:325:37: error: 'enableFan' was not declared in this scope
       if(setMenuPage==0){boolTemp = enableFan;}
                                     ^~~~~~~~~
8_LCD_Menu:329:14: error: 'enableFan' was not declared in this scope
           if(enableFan==1){enableFan=0;}else{enableFan=1;}
              ^~~~~~~~~
8_LCD_Menu:331:75: error: 'enableFan' was not declared in this scope
         if(digitalRead(buttonBack)==1){while(digitalRead(buttonBack)==1){}enableFan = boolTemp;cancelledMessageLCD();setMenuPage=0;}
                                                                           ^~~~~~~~~
8_LCD_Menu:402:10: error: 'enableWiFi' was not declared in this scope
       if(enableWiFi==1){lcd.print("ENABLED       ");}
          ^~~~~~~~~~
8_LCD_Menu:406:37: error: 'enableWiFi' was not declared in this scope
       if(setMenuPage==0){boolTemp = enableWiFi;}
                                     ^~~~~~~~~~
8_LCD_Menu:410:14: error: 'enableWiFi' was not declared in this scope
           if(enableWiFi==1){enableWiFi=0;}else{enableWiFi=1;}
              ^~~~~~~~~~
8_LCD_Menu:412:75: error: 'enableWiFi' was not declared in this scope
         if(digitalRead(buttonBack)==1){while(digitalRead(buttonBack)==1){}enableWiFi = boolTemp;cancelledMessageLCD();setMenuPage=0;}
                                                                           ^~~~~~~~~~
8_LCD_Menu:535:5: error: 'currentLCDMillis' was not declared in this scope
     currentLCDMillis = millis();
     ^~~~~~~~~~~~~~~~
F:\mppt-wifi\ARDUINO_MPPT_FIRMWARE_V1.1\8_LCD_Menu.ino:535:5: note: suggested alternative: 'currentSens'
     currentLCDMillis = millis();
     ^~~~~~~~~~~~~~~~
     currentSens
8_LCD_Menu:536:25: error: 'prevLCDMillis' was not declared in this scope
     if(currentLCDMillis-prevLCDMillis>=millisLCDInterval&&enableLCD==1){   //Run routine every millisLCDInterval (ms)
                         ^~~~~~~~~~~~~
8_LCD_Menu:536:59: error: 'enableLCD' was not declared in this scope
     if(currentLCDMillis-prevLCDMillis>=millisLCDInterval&&enableLCD==1){   //Run routine every millisLCDInterval (ms)
                                                           ^~~~~~~~~
"WiFi.h" 对应多个库
 已使用： D:\Program Files (x86)\Arduino\hardware\espressif\esp32\libraries\WiFi
 未使用：d:\Program Files (x86)\Arduino\libraries\WiFi
exit status 1
expected unqualified-id before 'bool'

**Comment by cyberangel22k** [comment]
thanks for bringing this up. Will fix it now.

**Comment by cyberangel22k** [comment]
Fixed
