### ISSUE TITLE
Emergency, Reverse Boot operation voltage has exceeded the PV system voltage,

### ISSUE THREAD

**Issue by he77PC011** [cyberangel22k/FUGU-ARDUINO-MPPT-FIRMWARE#6]
Emergency, the sudden discovery of solar cell off today, MOS component damage, after observation operation data analysis, because the PV power suddenly off, the system is damaged by a buck reverse Boot working straight-channel PV voltage exceeding the mos limit MOS fault. The reverse Boot operates at a voltage that exceeds the PV system voltage. If possible, it is recommended to increase the system safety voltage and force off the GPIO32 and IR2104 -3-SD outputs when the voltage exceeds the set value

**Comment by cyberangel22k** [comment]
I cannot understand the translation.
