### ISSUE TITLE
The system did not shut down IR2104 2104 (EN)   buck_Disable  buck_EN,  NO，LOW

### ISSUE THREAD

**Issue by he77PC011** [cyberangel22k/FUGU-ARDUINO-MPPT-FIRMWARE#7]
![360截图20221209063131706](https://user-images.githubusercontent.com/87251554/206581402-8bd2aba1-e7ab-44f5-8ddd-8d108e7d1c1a.jpg)
![461-1024](https://user-images.githubusercontent.com/87251554/206581973-6462b935-08b4-4dfe-80a6-d45909544036.jpg)

The system did not shut down IR2104 2104 (EN)   buck_Disable  buck_EN,  NO，LOW

**Comment by cyberangel22k** [comment]
I think you don't have enough panel to power your 48v battery. Also, why VO dropping? what is the capacity of your battery?

**Comment by cyberangel22k** [comment]
You need to add additional panels and make it close to 80v input. I will close this thread now.
