### ISSUE TITLE
Question about solar panel

### ISSUE THREAD

**Issue by NickDolfin** [cyberangel22k/FUGU-ARDUINO-MPPT-FIRMWARE#8]
Hi,

I have a Powerfilm panel that has a low Vmpp of around 15.7V.

Can this circuit/firmware be used to charge a 14.4 LiFePO4 battery?

Thanks

**Comment by cyberangel22k** [comment]
Negative. You will have IUV errors. You can get another one and wire it in series and it will work perfectly.
