### ISSUE TITLE
50W 17,6Vmp Panel and 12,6V 3S 4P Liion Battery - MPPT starts new every Minute

### ISSUE THREAD

**Issue by fellpower** [cyberangel22k/FUGU-ARDUINO-MPPT-FIRMWARE#9]
Hey

As discribed i have that panel and that battery. if im getting like 30-50W, the MPPT works - and charges the battery.

But after a few minutes, the MPPT drops down the voltage near the battery (and not search for mppt) - and then shuts down. then it starts again, with open ends solar voltage (+20V), with the message: Power source detected.

My solar voltage / Power / current looks like a sawtooth

<img width="322" alt="mppt1" src="https://github.com/cyberangel22k/FUGU-ARDUINO-MPPT-FIRMWARE/assets/73786796/fd8e7bd9-4783-4784-b8a4-a37964359f2b">

can u fix that plz?

**Comment by cyberangel22k** [comment]
try the latest update. I noticed I haven't included the IUV error protection in the past builds. You can download the sketch directly instead of the ones on the release page.
